import type { Metadata } from "next";
import Link from "next/link";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Contractor Permit Software for Hawaii — DCCA & DPP Tracking · BlueWave Projects",
  description:
    "AI-powered permit tracking for Hawaii contractors. DCCA license renewals, DPP building permit status, sub-license verification, and pre-submission document checks — built for Hawaii's GCs and trades.",
  keywords: [
    "contractor permit software Hawaii",
    "DCCA license tracking Hawaii",
    "Hawaii building permit software",
    "DPP permit tracking Hawaii",
    "Hawaii contractor compliance software",
    "DCCA renewal reminders Hawaii",
    "Hawaii general contractor software",
    "PermitPaddler Hawaii",
  ],
  alternates: { canonical: "https://bluewaveprojects.com/contractor-permit-software-hawaii" },
  openGraph: {
    title: "Contractor Permit Software for Hawaii — DCCA & DPP Tracking",
    description:
      "DCCA license renewals, DPP permit status, sub verification, pre-submission checks — built for Hawaii GCs and trades.",
    url: "https://bluewaveprojects.com/contractor-permit-software-hawaii",
    siteName: "BlueWave Projects",
    type: "website",
    images: [{ url: "/og-default.png", width: 1200, height: 630 }],
  },
};

const features = [
  {
    title: "DCCA license expiration alerts",
    description: "90/60/30-day reminders for your C license, specialty licenses, bond, insurance certificate, and workers' comp policy — pulled from your uploaded documents.",
  },
  {
    title: "DPP permit status tracking",
    description: "Monitor building, electrical, plumbing, and grading permit status across all active jobs without daily manual portal checks. Changes surface to your dashboard.",
  },
  {
    title: "Pre-submission document checklist",
    description: "Know what documents the county DPP requires for your specific project type before you submit. Catch the gaps before the counter rejects your package.",
  },
  {
    title: "Sub-contractor license verification",
    description: "Verify every sub's DCCA license at project start and flag expirations before work begins — not after the county inspector arrives.",
  },
  {
    title: "Permit chain dependency mapping",
    description: "See which downstream permits depend on upstream approvals. Know the critical path before a delay blindsides your schedule.",
  },
  {
    title: "Renewal document generation",
    description: "DCCA renewal checklists auto-generated by license type. Know exactly what you need to gather, in advance, every time.",
  },
];

const licenseTypes = [
  { code: "A", label: "General Engineering Contractor" },
  { code: "B", label: "General Building Contractor" },
  { code: "C", label: "Specialty Contractor" },
  { code: "D", label: "Specialty Contractor — Electrical" },
  { code: "E", label: "Specialty Contractor — Plumbing" },
  { code: "F", label: "Specialty Contractor — Fire Protection" },
];

export default function ContractorPermitHawaiiPage() {
  return (
    <main className="ocean-gradient min-h-screen">
      <Nav />

      {/* Hero */}
      <section className="px-6 pt-32 pb-20 max-w-5xl mx-auto">
        <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-wave-500/10 border border-wave-500/25 text-wave-300/90 text-xs uppercase tracking-[0.16em] mb-6 font-mono">
          Hawaii Contractor Software
        </div>
        <h1 className="text-4xl sm:text-6xl font-bold tracking-tight leading-tight mb-6 max-w-4xl">
          Permit tracking software{" "}
          <span className="text-gradient">built for Hawaii contractors</span>
        </h1>
        <p className="text-xl text-white/60 leading-relaxed max-w-2xl mb-10">
          DCCA license renewals, DPP permit status, sub verification, pre-submission document checks — all in one place. Built around Hawaii's actual regulatory structure, not adapted from a mainland product.
        </p>
        <div className="flex flex-col sm:flex-row gap-4">
          <Link href="/booking" className="btn-primary px-8 py-3.5 rounded-full text-sm font-semibold text-white text-center">
            Book a call →
          </Link>
          <Link href="/scope" className="px-8 py-3.5 rounded-full text-sm font-semibold text-white/80 border border-white/15 hover:border-white/30 transition-colors text-center">
            Try the AI Scope Tool →
          </Link>
        </div>
      </section>

      {/* Cost of a missed permit */}
      <section className="px-6 py-16 max-w-5xl mx-auto">
        <div className="rounded-2xl border border-white/8 bg-white/3 p-8 sm:p-10">
          <h2 className="text-2xl font-bold mb-4">What a missed permit costs in Hawaii</h2>
          <div className="grid sm:grid-cols-3 gap-6 mt-6">
            <div>
              <div className="text-3xl font-bold text-wave-400 mb-2">2–6 wks</div>
              <p className="text-sm text-white/50">Average delay from a rejected DPP permit package due to missing documentation</p>
            </div>
            <div>
              <div className="text-3xl font-bold text-wave-400 mb-2">$0</div>
              <p className="text-sm text-white/50">Billable work if your DCCA C license lapses during an active project — legally, you can't bill for it</p>
            </div>
            <div>
              <div className="text-3xl font-bold text-wave-400 mb-2">20+</div>
              <p className="text-sm text-white/50">Documents with separate expiration dates on a typical 3-job pipeline — each one a potential stoppage</p>
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="px-6 py-16 max-w-5xl mx-auto">
        <h2 className="text-2xl sm:text-3xl font-bold mb-10">What the software tracks</h2>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((f) => (
            <div key={f.title} className="rounded-2xl border border-white/8 bg-white/3 p-6">
              <h3 className="font-semibold text-white mb-2">{f.title}</h3>
              <p className="text-sm text-white/50 leading-relaxed">{f.description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* License types */}
      <section className="px-6 py-16 max-w-5xl mx-auto">
        <h2 className="text-2xl sm:text-3xl font-bold mb-6">DCCA license types covered</h2>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {licenseTypes.map((l) => (
            <div key={l.code} className="rounded-xl border border-white/8 bg-white/3 px-4 py-3">
              <span className="text-xs font-mono text-wave-400 mr-2">Class {l.code}</span>
              <span className="text-sm text-white/60">{l.label}</span>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="px-6 py-20 max-w-5xl mx-auto">
        <div className="rounded-3xl border border-wave-500/25 bg-gradient-to-br from-ocean-900/50 via-black/40 to-black p-10 text-center">
          <h2 className="text-3xl font-bold mb-4">Still tracking permits in a spreadsheet?</h2>
          <p className="text-white/60 mb-8 max-w-xl mx-auto">
            Book a 30-minute call. We'll map your current permit workflow and show you exactly where the risk is — no pitch, just an honest operational audit.
          </p>
          <Link href="/booking" className="btn-primary px-8 py-3.5 rounded-full text-sm font-semibold text-white inline-block">
            Book a free permit audit →
          </Link>
        </div>
      </section>

      {/* Related reading */}
      <section className="px-6 pb-20 max-w-5xl mx-auto">
        <h2 className="text-xl font-semibold mb-6 text-white/70">Related reading</h2>
        <Link href="/blog/automating-dcca-permit-tracking-hawaii" className="text-wave-400 hover:text-wave-300 transition-colors text-sm">
          Automating DCCA permit tracking in Hawaii: what's possible in 2026 →
        </Link>
      </section>

      <Footer />

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "SoftwareApplication",
            name: "PermitPaddler — Hawaii Contractor Permit Software",
            description: "AI-powered permit tracking for Hawaii contractors. DCCA license renewals, DPP permit status, sub verification, pre-submission document checks.",
            url: "https://bluewaveprojects.com/contractor-permit-software-hawaii",
            applicationCategory: "BusinessApplication",
            operatingSystem: "Web",
            creator: {
              "@type": "Organization",
              name: "BlueWave Projects",
              url: "https://bluewaveprojects.com",
              address: {
                "@type": "PostalAddress",
                streetAddress: "440 Lewers St, Suite 603",
                addressLocality: "Honolulu",
                addressRegion: "HI",
                postalCode: "96815",
                addressCountry: "US",
              },
            },
            audience: { "@type": "Audience", audienceType: "Hawaii general contractors, specialty trades, and property managers" },
            areaServed: { "@type": "State", name: "Hawaii" },
          }),
        }}
      />
    </main>
  );
}
